// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { backTranslateFromBrailleApiBackTranslatePost, brailleToSpeechApiBrailleToSpeechPost, healthCheckGet, listTablesApiTablesGet, listVoicesApiVoicesGet, ocrRecognizeApiOcrPost, ocrToBrailleApiOcrToBraillePost, type Options, speechToBrailleApiSpeechToBraillePost, testTranslationApiTestTranslationGet, transcribeSpeechApiTranscribePost, translateToBrailleApiTranslatePost } from '../sdk.gen';
import type { BackTranslateFromBrailleApiBackTranslatePostData, BackTranslateFromBrailleApiBackTranslatePostError, BackTranslateFromBrailleApiBackTranslatePostResponse, BrailleToSpeechApiBrailleToSpeechPostData, BrailleToSpeechApiBrailleToSpeechPostError, HealthCheckGetData, HealthCheckGetResponse, ListTablesApiTablesGetData, ListTablesApiTablesGetResponse, ListVoicesApiVoicesGetData, ListVoicesApiVoicesGetResponse, OcrRecognizeApiOcrPostData, OcrRecognizeApiOcrPostError, OcrRecognizeApiOcrPostResponse, OcrToBrailleApiOcrToBraillePostData, OcrToBrailleApiOcrToBraillePostError, OcrToBrailleApiOcrToBraillePostResponse, SpeechToBrailleApiSpeechToBraillePostData, SpeechToBrailleApiSpeechToBraillePostError, SpeechToBrailleApiSpeechToBraillePostResponse, TestTranslationApiTestTranslationGetData, TestTranslationApiTestTranslationGetResponse, TranscribeSpeechApiTranscribePostData, TranscribeSpeechApiTranscribePostError, TranscribeSpeechApiTranscribePostResponse, TranslateToBrailleApiTranslatePostData, TranslateToBrailleApiTranslatePostError, TranslateToBrailleApiTranslatePostResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthCheckGetQueryKey = (options?: Options<HealthCheckGetData>) => createQueryKey('healthCheckGet', options);

/**
 * Health Check
 *
 * Health check endpoint with ASR and TTS status.
 */
export const healthCheckGetOptions = (options?: Options<HealthCheckGetData>) => queryOptions<HealthCheckGetResponse, DefaultError, HealthCheckGetResponse, ReturnType<typeof healthCheckGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthCheckGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckGetQueryKey(options)
});

export const listTablesApiTablesGetQueryKey = (options?: Options<ListTablesApiTablesGetData>) => createQueryKey('listTablesApiTablesGet', options);

/**
 * List Tables
 *
 * List all available braille translation tables.
 *
 * Scans liblouis table directories and returns metadata for each table.
 */
export const listTablesApiTablesGetOptions = (options?: Options<ListTablesApiTablesGetData>) => queryOptions<ListTablesApiTablesGetResponse, DefaultError, ListTablesApiTablesGetResponse, ReturnType<typeof listTablesApiTablesGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTablesApiTablesGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTablesApiTablesGetQueryKey(options)
});

/**
 * Translate To Braille
 *
 * Translate text to braille using the specified table.
 *
 * Returns Unicode braille characters that can be displayed or sent to a braille display.
 */
export const translateToBrailleApiTranslatePostMutation = (options?: Partial<Options<TranslateToBrailleApiTranslatePostData>>): UseMutationOptions<TranslateToBrailleApiTranslatePostResponse, TranslateToBrailleApiTranslatePostError, Options<TranslateToBrailleApiTranslatePostData>> => {
    const mutationOptions: UseMutationOptions<TranslateToBrailleApiTranslatePostResponse, TranslateToBrailleApiTranslatePostError, Options<TranslateToBrailleApiTranslatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await translateToBrailleApiTranslatePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Back Translate From Braille
 *
 * Back-translate braille to text using the specified table.
 *
 * Useful for processing input from braille keyboards.
 */
export const backTranslateFromBrailleApiBackTranslatePostMutation = (options?: Partial<Options<BackTranslateFromBrailleApiBackTranslatePostData>>): UseMutationOptions<BackTranslateFromBrailleApiBackTranslatePostResponse, BackTranslateFromBrailleApiBackTranslatePostError, Options<BackTranslateFromBrailleApiBackTranslatePostData>> => {
    const mutationOptions: UseMutationOptions<BackTranslateFromBrailleApiBackTranslatePostResponse, BackTranslateFromBrailleApiBackTranslatePostError, Options<BackTranslateFromBrailleApiBackTranslatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await backTranslateFromBrailleApiBackTranslatePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const testTranslationApiTestTranslationGetQueryKey = (options?: Options<TestTranslationApiTestTranslationGetData>) => createQueryKey('testTranslationApiTestTranslationGet', options);

/**
 * Test Translation
 *
 * Test endpoint with a sample translation using English UEB Grade 2.
 *
 * Useful for verifying the system is working without client setup.
 */
export const testTranslationApiTestTranslationGetOptions = (options?: Options<TestTranslationApiTestTranslationGetData>) => queryOptions<TestTranslationApiTestTranslationGetResponse, DefaultError, TestTranslationApiTestTranslationGetResponse, ReturnType<typeof testTranslationApiTestTranslationGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await testTranslationApiTestTranslationGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: testTranslationApiTestTranslationGetQueryKey(options)
});

/**
 * Transcribe Speech
 *
 * Transcribe speech from an audio file using whisper.cpp.
 *
 * Accepts various audio formats and returns transcribed text.
 *
 * Args:
 * audio: Audio file upload
 * language: Language code (e.g., 'en', 'es') - required
 * task: 'transcribe' (in original language) or 'translate' (to English)
 * word_timestamps: Include word-level timestamps in response
 */
export const transcribeSpeechApiTranscribePostMutation = (options?: Partial<Options<TranscribeSpeechApiTranscribePostData>>): UseMutationOptions<TranscribeSpeechApiTranscribePostResponse, TranscribeSpeechApiTranscribePostError, Options<TranscribeSpeechApiTranscribePostData>> => {
    const mutationOptions: UseMutationOptions<TranscribeSpeechApiTranscribePostResponse, TranscribeSpeechApiTranscribePostError, Options<TranscribeSpeechApiTranscribePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await transcribeSpeechApiTranscribePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Speech To Braille
 *
 * Complete pipeline: Speech -> Text -> Braille
 *
 * Transcribes audio and immediately translates to braille.
 * This is the main endpoint for the deafblind communication device.
 *
 * Args:
 * audio: Audio file with speech
 * braille_table: Braille table to use (default: English UEB Grade 2)
 * language: Language code (e.g., 'en', 'es') - required
 * task: 'transcribe' or 'translate'
 * word_timestamps: Include word-level timestamps in response
 */
export const speechToBrailleApiSpeechToBraillePostMutation = (options?: Partial<Options<SpeechToBrailleApiSpeechToBraillePostData>>): UseMutationOptions<SpeechToBrailleApiSpeechToBraillePostResponse, SpeechToBrailleApiSpeechToBraillePostError, Options<SpeechToBrailleApiSpeechToBraillePostData>> => {
    const mutationOptions: UseMutationOptions<SpeechToBrailleApiSpeechToBraillePostResponse, SpeechToBrailleApiSpeechToBraillePostError, Options<SpeechToBrailleApiSpeechToBraillePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await speechToBrailleApiSpeechToBraillePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Braille To Speech
 *
 * Convert braille text to speech audio.
 *
 * Back-translates braille to text, then synthesizes speech.
 * Returns WAV audio with metadata in custom headers.
 */
export const brailleToSpeechApiBrailleToSpeechPostMutation = (options?: Partial<Options<BrailleToSpeechApiBrailleToSpeechPostData>>): UseMutationOptions<unknown, BrailleToSpeechApiBrailleToSpeechPostError, Options<BrailleToSpeechApiBrailleToSpeechPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, BrailleToSpeechApiBrailleToSpeechPostError, Options<BrailleToSpeechApiBrailleToSpeechPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await brailleToSpeechApiBrailleToSpeechPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listVoicesApiVoicesGetQueryKey = (options?: Options<ListVoicesApiVoicesGetData>) => createQueryKey('listVoicesApiVoicesGet', options);

/**
 * List Voices
 *
 * List available TTS voices.
 */
export const listVoicesApiVoicesGetOptions = (options?: Options<ListVoicesApiVoicesGetData>) => queryOptions<ListVoicesApiVoicesGetResponse, DefaultError, ListVoicesApiVoicesGetResponse, ReturnType<typeof listVoicesApiVoicesGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listVoicesApiVoicesGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listVoicesApiVoicesGetQueryKey(options)
});

/**
 * Ocr Recognize
 *
 * Recognize text from an image using RapidOCR PP-OCRv5.
 *
 * Returns recognized text lines with confidence scores and bounding boxes.
 */
export const ocrRecognizeApiOcrPostMutation = (options?: Partial<Options<OcrRecognizeApiOcrPostData>>): UseMutationOptions<OcrRecognizeApiOcrPostResponse, OcrRecognizeApiOcrPostError, Options<OcrRecognizeApiOcrPostData>> => {
    const mutationOptions: UseMutationOptions<OcrRecognizeApiOcrPostResponse, OcrRecognizeApiOcrPostError, Options<OcrRecognizeApiOcrPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ocrRecognizeApiOcrPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Ocr To Braille
 *
 * Full pipeline: Image -> OCR -> Text -> Braille.
 *
 * Recognizes text from an image and translates it to braille.
 */
export const ocrToBrailleApiOcrToBraillePostMutation = (options?: Partial<Options<OcrToBrailleApiOcrToBraillePostData>>): UseMutationOptions<OcrToBrailleApiOcrToBraillePostResponse, OcrToBrailleApiOcrToBraillePostError, Options<OcrToBrailleApiOcrToBraillePostData>> => {
    const mutationOptions: UseMutationOptions<OcrToBrailleApiOcrToBraillePostResponse, OcrToBrailleApiOcrToBraillePostError, Options<OcrToBrailleApiOcrToBraillePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ocrToBrailleApiOcrToBraillePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
