// This file is auto-generated by @hey-api/openapi-ts

export const BackTranslationRequestSchema = {
    properties: {
        braille: {
            type: 'string',
            minLength: 1,
            title: 'Braille',
            description: 'Braille text to translate back'
        },
        table: {
            type: 'string',
            title: 'Table',
            description: 'Braille table filename to use'
        }
    },
    type: 'object',
    required: [
        'braille',
        'table'
    ],
    title: 'BackTranslationRequest',
    description: 'Request model for braille-to-text back-translation'
} as const;

export const BackTranslationResponseSchema = {
    properties: {
        original_braille: {
            type: 'string',
            title: 'Original Braille',
            description: 'Original braille input'
        },
        text: {
            type: 'string',
            title: 'Text',
            description: 'Back-translated text'
        },
        table_used: {
            type: 'string',
            title: 'Table Used',
            description: 'Table filename used'
        },
        success: {
            type: 'boolean',
            title: 'Success',
            description: 'Whether back-translation succeeded'
        }
    },
    type: 'object',
    required: [
        'original_braille',
        'text',
        'table_used',
        'success'
    ],
    title: 'BackTranslationResponse',
    description: 'Response model for back-translation'
} as const;

export const Body_speech_to_braille_api_speech_to_braille_postSchema = {
    properties: {
        audio: {
            type: 'string',
            format: 'binary',
            title: 'Audio',
            description: 'Audio file'
        }
    },
    type: 'object',
    required: [
        'audio'
    ],
    title: 'Body_speech_to_braille_api_speech_to_braille_post'
} as const;

export const Body_transcribe_speech_api_transcribe_postSchema = {
    properties: {
        audio: {
            type: 'string',
            format: 'binary',
            title: 'Audio',
            description: 'Audio file (WAV, MP3, OGG, etc.)'
        }
    },
    type: 'object',
    required: [
        'audio'
    ],
    title: 'Body_transcribe_speech_api_transcribe_post'
} as const;

export const BrailleTableSchema = {
    properties: {
        filename: {
            type: 'string',
            title: 'Filename',
            description: 'Table filename (e.g., en-us-g2.ctb)'
        },
        display_name: {
            type: 'string',
            title: 'Display Name',
            description: 'Human-readable name'
        },
        language: {
            type: 'string',
            title: 'Language',
            description: 'Language code (ISO 639)'
        },
        grade: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade',
            description: 'Braille grade (g1, g2, etc.)'
        }
    },
    type: 'object',
    required: [
        'filename',
        'display_name',
        'language'
    ],
    title: 'BrailleTable',
    description: 'Represents a braille translation table'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        liblouis_version: {
            type: 'string',
            title: 'Liblouis Version'
        },
        asr_status: {
            type: 'string',
            title: 'Asr Status'
        },
        asr_model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Asr Model'
        },
        asr_device: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Asr Device'
        }
    },
    type: 'object',
    required: [
        'status',
        'message',
        'liblouis_version',
        'asr_status'
    ],
    title: 'HealthResponse',
    description: 'Health check response'
} as const;

export const SegmentTimestampSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id',
            description: 'Segment ID'
        },
        start: {
            type: 'number',
            title: 'Start',
            description: 'Segment start time in seconds'
        },
        end: {
            type: 'number',
            title: 'End',
            description: 'Segment end time in seconds'
        },
        text: {
            type: 'string',
            title: 'Text',
            description: 'Segment text'
        },
        words: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/WordTimestamp'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Words',
            description: 'Word-level timestamps'
        },
        avg_logprob: {
            type: 'number',
            title: 'Avg Logprob',
            description: 'Average log probability'
        },
        no_speech_prob: {
            type: 'number',
            title: 'No Speech Prob',
            description: 'No speech probability'
        }
    },
    type: 'object',
    required: [
        'id',
        'start',
        'end',
        'text',
        'avg_logprob',
        'no_speech_prob'
    ],
    title: 'SegmentTimestamp',
    description: 'Segment-level information with word timestamps'
} as const;

export const SpeechToBrailleResponseSchema = {
    properties: {
        transcribed_text: {
            type: 'string',
            title: 'Transcribed Text',
            description: 'Transcribed speech'
        },
        braille: {
            type: 'string',
            title: 'Braille',
            description: 'Braille output'
        },
        language: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language',
            description: 'Detected language'
        },
        table_used: {
            type: 'string',
            title: 'Table Used',
            description: 'Braille table used'
        },
        audio_duration: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Audio Duration',
            description: 'Audio duration'
        },
        segments: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/SegmentTimestamp'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Segments',
            description: 'Segment timestamps'
        },
        success: {
            type: 'boolean',
            title: 'Success',
            description: 'Success status'
        }
    },
    type: 'object',
    required: [
        'transcribed_text',
        'braille',
        'table_used',
        'success'
    ],
    title: 'SpeechToBrailleResponse',
    description: 'Response for combined pipeline'
} as const;

export const TranscriptionResponseSchema = {
    properties: {
        text: {
            type: 'string',
            title: 'Text',
            description: 'Transcribed text'
        },
        language: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language',
            description: 'Detected or specified language'
        },
        duration: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration',
            description: 'Audio duration in seconds'
        },
        segments: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/SegmentTimestamp'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Segments',
            description: 'Segment timestamps with words'
        },
        success: {
            type: 'boolean',
            title: 'Success',
            description: 'Whether transcription succeeded'
        }
    },
    type: 'object',
    required: [
        'text',
        'success'
    ],
    title: 'TranscriptionResponse',
    description: 'Response model for speech transcription'
} as const;

export const TranslationRequestSchema = {
    properties: {
        text: {
            type: 'string',
            minLength: 1,
            title: 'Text',
            description: 'Text to translate to braille'
        },
        table: {
            type: 'string',
            title: 'Table',
            description: 'Braille table filename to use'
        }
    },
    type: 'object',
    required: [
        'text',
        'table'
    ],
    title: 'TranslationRequest',
    description: 'Request model for text-to-braille translation'
} as const;

export const TranslationResponseSchema = {
    properties: {
        original_text: {
            type: 'string',
            title: 'Original Text',
            description: 'Original input text'
        },
        braille: {
            type: 'string',
            title: 'Braille',
            description: 'Translated braille text (Unicode braille)'
        },
        table_used: {
            type: 'string',
            title: 'Table Used',
            description: 'Table filename used for translation'
        },
        success: {
            type: 'boolean',
            title: 'Success',
            description: 'Whether translation succeeded'
        }
    },
    type: 'object',
    required: [
        'original_text',
        'braille',
        'table_used',
        'success'
    ],
    title: 'TranslationResponse',
    description: 'Response model for braille translation'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const WordTimestampSchema = {
    properties: {
        word: {
            type: 'string',
            title: 'Word',
            description: 'The word text'
        },
        start: {
            type: 'number',
            title: 'Start',
            description: 'Start time in seconds'
        },
        end: {
            type: 'number',
            title: 'End',
            description: 'End time in seconds'
        },
        probability: {
            type: 'number',
            title: 'Probability',
            description: 'Word confidence probability'
        }
    },
    type: 'object',
    required: [
        'word',
        'start',
        'end',
        'probability'
    ],
    title: 'WordTimestamp',
    description: 'Word-level timestamp information'
} as const;
