// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { BackTranslateFromBrailleApiBackTranslatePostData, BackTranslateFromBrailleApiBackTranslatePostErrors, BackTranslateFromBrailleApiBackTranslatePostResponses, HealthCheckGetData, HealthCheckGetResponses, ListTablesApiTablesGetData, ListTablesApiTablesGetResponses, SpeechToBrailleApiSpeechToBraillePostData, SpeechToBrailleApiSpeechToBraillePostErrors, SpeechToBrailleApiSpeechToBraillePostResponses, TestTranslationApiTestTranslationGetData, TestTranslationApiTestTranslationGetResponses, TranscribeSpeechApiTranscribePostData, TranscribeSpeechApiTranscribePostErrors, TranscribeSpeechApiTranscribePostResponses, TranslateToBrailleApiTranslatePostData, TranslateToBrailleApiTranslatePostErrors, TranslateToBrailleApiTranslatePostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * Health check endpoint with ASR status
 */
export const healthCheckGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * List Tables
 *
 * List all available braille translation tables.
 *
 * Scans liblouis table directories and returns metadata for each table.
 */
export const listTablesApiTablesGet = <ThrowOnError extends boolean = false>(options?: Options<ListTablesApiTablesGetData, ThrowOnError>) => (options?.client ?? client).get<ListTablesApiTablesGetResponses, unknown, ThrowOnError>({ url: '/api/tables', ...options });

/**
 * Translate To Braille
 *
 * Translate text to braille using the specified table.
 *
 * Returns Unicode braille characters that can be displayed or sent to a braille display.
 */
export const translateToBrailleApiTranslatePost = <ThrowOnError extends boolean = false>(options: Options<TranslateToBrailleApiTranslatePostData, ThrowOnError>) => (options.client ?? client).post<TranslateToBrailleApiTranslatePostResponses, TranslateToBrailleApiTranslatePostErrors, ThrowOnError>({
    url: '/api/translate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Back Translate From Braille
 *
 * Back-translate braille to text using the specified table.
 *
 * Useful for processing input from braille keyboards.
 */
export const backTranslateFromBrailleApiBackTranslatePost = <ThrowOnError extends boolean = false>(options: Options<BackTranslateFromBrailleApiBackTranslatePostData, ThrowOnError>) => (options.client ?? client).post<BackTranslateFromBrailleApiBackTranslatePostResponses, BackTranslateFromBrailleApiBackTranslatePostErrors, ThrowOnError>({
    url: '/api/back-translate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Test Translation
 *
 * Test endpoint with a sample translation using English UEB Grade 2.
 *
 * Useful for verifying the system is working without client setup.
 */
export const testTranslationApiTestTranslationGet = <ThrowOnError extends boolean = false>(options?: Options<TestTranslationApiTestTranslationGetData, ThrowOnError>) => (options?.client ?? client).get<TestTranslationApiTestTranslationGetResponses, unknown, ThrowOnError>({ url: '/api/test-translation', ...options });

/**
 * Transcribe Speech
 *
 * Transcribe speech from an audio file using faster-whisper.
 *
 * Accepts various audio formats and returns transcribed text.
 * The model auto-detects language if not specified.
 *
 * Args:
 * audio: Audio file upload
 * language: Optional language code (e.g., 'en', 'es')
 * task: 'transcribe' (in original language) or 'translate' (to English)
 * word_timestamps: Include word-level timestamps in response
 */
export const transcribeSpeechApiTranscribePost = <ThrowOnError extends boolean = false>(options: Options<TranscribeSpeechApiTranscribePostData, ThrowOnError>) => (options.client ?? client).post<TranscribeSpeechApiTranscribePostResponses, TranscribeSpeechApiTranscribePostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/transcribe',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Speech To Braille
 *
 * Complete pipeline: Speech → Text → Braille
 *
 * Transcribes audio and immediately translates to braille.
 * This is the main endpoint for the deafblind communication device.
 *
 * Args:
 * audio: Audio file with speech
 * braille_table: Braille table to use (default: English UEB Grade 2)
 * language: Optional speech language code
 * task: 'transcribe' or 'translate'
 * word_timestamps: Include word-level timestamps in response
 */
export const speechToBrailleApiSpeechToBraillePost = <ThrowOnError extends boolean = false>(options: Options<SpeechToBrailleApiSpeechToBraillePostData, ThrowOnError>) => (options.client ?? client).post<SpeechToBrailleApiSpeechToBraillePostResponses, SpeechToBrailleApiSpeechToBraillePostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/speech-to-braille',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
