// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * BackTranslationRequest
 *
 * Request model for braille-to-text back-translation.
 */
export type BackTranslationRequest = {
    /**
     * Braille
     *
     * Braille text to translate back
     */
    braille: string;
    /**
     * Table
     *
     * Braille table filename to use
     */
    table: string;
};

/**
 * BackTranslationResponse
 *
 * Response model for back-translation.
 */
export type BackTranslationResponse = {
    /**
     * Original Braille
     *
     * Original braille input
     */
    original_braille: string;
    /**
     * Text
     *
     * Back-translated text
     */
    text: string;
    /**
     * Table Used
     *
     * Table filename used
     */
    table_used: string;
    /**
     * Success
     *
     * Whether back-translation succeeded
     */
    success: boolean;
};

/**
 * Body_ocr_recognize_api_ocr_post
 */
export type BodyOcrRecognizeApiOcrPost = {
    /**
     * Image
     *
     * Image file (PNG, JPG, BMP, TIFF, WebP)
     */
    image: Blob | File;
};

/**
 * Body_ocr_to_braille_api_ocr_to_braille_post
 */
export type BodyOcrToBrailleApiOcrToBraillePost = {
    /**
     * Image
     *
     * Image file (PNG, JPG, BMP, TIFF, WebP)
     */
    image: Blob | File;
};

/**
 * Body_speech_to_braille_api_speech_to_braille_post
 */
export type BodySpeechToBrailleApiSpeechToBraillePost = {
    /**
     * Audio
     *
     * Audio file
     */
    audio: Blob | File;
};

/**
 * Body_transcribe_speech_api_transcribe_post
 */
export type BodyTranscribeSpeechApiTranscribePost = {
    /**
     * Audio
     *
     * Audio file (WAV, MP3, OGG, etc.)
     */
    audio: Blob | File;
};

/**
 * BrailleTable
 *
 * Represents a braille translation table.
 */
export type BrailleTable = {
    /**
     * Filename
     *
     * Table filename (e.g., en-us-g2.ctb)
     */
    filename: string;
    /**
     * Display Name
     *
     * Human-readable name
     */
    display_name: string;
    /**
     * Language
     *
     * Language code (ISO 639)
     */
    language: string;
    /**
     * Grade
     *
     * Braille grade (g1, g2, etc.)
     */
    grade?: string | null;
};

/**
 * BrailleToSpeechRequest
 *
 * Request model for braille-to-speech synthesis.
 */
export type BrailleToSpeechRequest = {
    /**
     * Braille
     *
     * Braille text to convert to speech
     */
    braille: string;
    /**
     * Table
     *
     * Braille table filename for back-translation
     */
    table: string;
    /**
     * Voice Id
     *
     * Voice model ID (uses default if not specified)
     */
    voice_id?: string | null;
    /**
     * Length Scale
     *
     * Speech speed (0.5=half, 1.0=normal, 2.0=double)
     */
    length_scale?: number | null;
    /**
     * Noise Scale
     *
     * Speech variation (lower=robotic, higher=expressive)
     */
    noise_scale?: number | null;
    /**
     * Noise W
     *
     * Phoneme duration variation
     */
    noise_w?: number | null;
    /**
     * Volume
     *
     * Volume (0.0=mute, 1.0=normal, 2.0=double)
     */
    volume?: number | null;
    /**
     * Normalize Audio
     *
     * Normalize audio to consistent volume
     */
    normalize_audio?: boolean | null;
    /**
     * Use preset configuration
     */
    preset?: TtsPreset | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Health check response.
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Liblouis Version
     */
    liblouis_version: string;
    /**
     * Asr Status
     */
    asr_status: string;
    /**
     * Asr Model
     */
    asr_model?: string | null;
    /**
     * Asr Device
     */
    asr_device?: string | null;
    /**
     * Tts Status
     */
    tts_status?: string | null;
    /**
     * Tts Voices
     */
    tts_voices?: Array<string> | null;
    /**
     * Ocr Status
     */
    ocr_status?: string | null;
    /**
     * Ocr Languages
     */
    ocr_languages?: Array<string> | null;
};

/**
 * OCRLine
 *
 * A single recognized text line from OCR.
 */
export type OcrLine = {
    /**
     * Text
     */
    text: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Bbox
     */
    bbox: Array<Array<number>>;
};

/**
 * OCRResponse
 *
 * OCR-only response.
 */
export type OcrResponse = {
    /**
     * Lines
     */
    lines: Array<OcrLine>;
    /**
     * Full Text
     */
    full_text: string;
    /**
     * Language
     */
    language: string;
    /**
     * Success
     */
    success: boolean;
};

/**
 * OCRToBrailleResponse
 *
 * Full OCR-to-Braille pipeline response.
 */
export type OcrToBrailleResponse = {
    /**
     * Lines
     */
    lines: Array<OcrLine>;
    /**
     * Full Text
     */
    full_text: string;
    /**
     * Braille
     */
    braille: string;
    /**
     * Language
     */
    language: string;
    /**
     * Table Used
     */
    table_used: string;
    /**
     * Success
     */
    success: boolean;
};

/**
 * SegmentTimestamp
 *
 * Segment-level information with word timestamps.
 */
export type SegmentTimestamp = {
    /**
     * Id
     *
     * Segment ID
     */
    id: number;
    /**
     * Start
     *
     * Segment start time in seconds
     */
    start: number;
    /**
     * End
     *
     * Segment end time in seconds
     */
    end: number;
    /**
     * Text
     *
     * Segment text
     */
    text: string;
    /**
     * Words
     *
     * Word-level timestamps
     */
    words?: Array<WordTimestamp> | null;
    /**
     * Avg Logprob
     *
     * Average log probability
     */
    avg_logprob: number;
    /**
     * No Speech Prob
     *
     * No speech probability
     */
    no_speech_prob: number;
};

/**
 * SpeechToBrailleResponse
 *
 * Response for combined speech-to-text-to-braille pipeline.
 */
export type SpeechToBrailleResponse = {
    /**
     * Transcribed Text
     *
     * Transcribed speech
     */
    transcribed_text: string;
    /**
     * Braille
     *
     * Braille output
     */
    braille: string;
    /**
     * Language
     *
     * Detected language
     */
    language?: string | null;
    /**
     * Table Used
     *
     * Braille table used
     */
    table_used: string;
    /**
     * Audio Duration
     *
     * Audio duration
     */
    audio_duration?: number | null;
    /**
     * Segments
     *
     * Segment timestamps
     */
    segments?: Array<SegmentTimestamp> | null;
    /**
     * Success
     *
     * Success status
     */
    success: boolean;
};

/**
 * TTSPreset
 *
 * Pre-configured TTS settings for common use cases.
 */
export const TtsPreset = {
    NATURAL: 'natural',
    CLEAR: 'clear',
    FAST: 'fast',
    SLOW: 'slow',
    LOUD: 'loud'
} as const;

/**
 * TTSPreset
 *
 * Pre-configured TTS settings for common use cases.
 */
export type TtsPreset = typeof TtsPreset[keyof typeof TtsPreset];

/**
 * TranscriptionResponse
 *
 * Response model for speech transcription.
 */
export type TranscriptionResponse = {
    /**
     * Text
     *
     * Transcribed text
     */
    text: string;
    /**
     * Language
     *
     * Detected or specified language
     */
    language?: string | null;
    /**
     * Duration
     *
     * Audio duration in seconds
     */
    duration?: number | null;
    /**
     * Segments
     *
     * Segment timestamps with words
     */
    segments?: Array<SegmentTimestamp> | null;
    /**
     * Success
     *
     * Whether transcription succeeded
     */
    success: boolean;
};

/**
 * TranslationRequest
 *
 * Request model for text-to-braille translation.
 */
export type TranslationRequest = {
    /**
     * Text
     *
     * Text to translate to braille
     */
    text: string;
    /**
     * Table
     *
     * Braille table filename to use
     */
    table: string;
};

/**
 * TranslationResponse
 *
 * Response model for braille translation.
 */
export type TranslationResponse = {
    /**
     * Original Text
     *
     * Original input text
     */
    original_text: string;
    /**
     * Braille
     *
     * Translated braille text (Unicode braille)
     */
    braille: string;
    /**
     * Table Used
     *
     * Table filename used for translation
     */
    table_used: string;
    /**
     * Success
     *
     * Whether translation succeeded
     */
    success: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VoiceInfo
 *
 * Information about an available TTS voice.
 */
export type VoiceInfo = {
    /**
     * Voice Id
     *
     * Voice model identifier
     */
    voice_id: string;
    /**
     * Language
     *
     * Language code (e.g., en_US)
     */
    language: string;
    /**
     * Quality
     *
     * Voice quality level (e.g., medium)
     */
    quality: string;
};

/**
 * WordTimestamp
 *
 * Word-level timestamp information.
 */
export type WordTimestamp = {
    /**
     * Word
     *
     * The word text
     */
    word: string;
    /**
     * Start
     *
     * Start time in seconds
     */
    start: number;
    /**
     * End
     *
     * End time in seconds
     */
    end: number;
    /**
     * Probability
     *
     * Word confidence probability
     */
    probability: number;
};

export type HealthCheckGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type HealthCheckGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckGetResponse = HealthCheckGetResponses[keyof HealthCheckGetResponses];

export type ListTablesApiTablesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tables';
};

export type ListTablesApiTablesGetResponses = {
    /**
     * Response List Tables Api Tables Get
     *
     * Successful Response
     */
    200: Array<BrailleTable>;
};

export type ListTablesApiTablesGetResponse = ListTablesApiTablesGetResponses[keyof ListTablesApiTablesGetResponses];

export type TranslateToBrailleApiTranslatePostData = {
    body: TranslationRequest;
    path?: never;
    query?: never;
    url: '/api/translate';
};

export type TranslateToBrailleApiTranslatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranslateToBrailleApiTranslatePostError = TranslateToBrailleApiTranslatePostErrors[keyof TranslateToBrailleApiTranslatePostErrors];

export type TranslateToBrailleApiTranslatePostResponses = {
    /**
     * Successful Response
     */
    200: TranslationResponse;
};

export type TranslateToBrailleApiTranslatePostResponse = TranslateToBrailleApiTranslatePostResponses[keyof TranslateToBrailleApiTranslatePostResponses];

export type BackTranslateFromBrailleApiBackTranslatePostData = {
    body: BackTranslationRequest;
    path?: never;
    query?: never;
    url: '/api/back-translate';
};

export type BackTranslateFromBrailleApiBackTranslatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BackTranslateFromBrailleApiBackTranslatePostError = BackTranslateFromBrailleApiBackTranslatePostErrors[keyof BackTranslateFromBrailleApiBackTranslatePostErrors];

export type BackTranslateFromBrailleApiBackTranslatePostResponses = {
    /**
     * Successful Response
     */
    200: BackTranslationResponse;
};

export type BackTranslateFromBrailleApiBackTranslatePostResponse = BackTranslateFromBrailleApiBackTranslatePostResponses[keyof BackTranslateFromBrailleApiBackTranslatePostResponses];

export type TestTranslationApiTestTranslationGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test-translation';
};

export type TestTranslationApiTestTranslationGetResponses = {
    /**
     * Successful Response
     */
    200: TranslationResponse;
};

export type TestTranslationApiTestTranslationGetResponse = TestTranslationApiTestTranslationGetResponses[keyof TestTranslationApiTestTranslationGetResponses];

export type TranscribeSpeechApiTranscribePostData = {
    body: BodyTranscribeSpeechApiTranscribePost;
    path?: never;
    query: {
        /**
         * Language
         *
         * Language code (e.g., 'en', 'es') - required
         */
        language: string;
        /**
         * Task
         */
        task?: string;
        /**
         * Word Timestamps
         */
        word_timestamps?: boolean;
    };
    url: '/api/transcribe';
};

export type TranscribeSpeechApiTranscribePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranscribeSpeechApiTranscribePostError = TranscribeSpeechApiTranscribePostErrors[keyof TranscribeSpeechApiTranscribePostErrors];

export type TranscribeSpeechApiTranscribePostResponses = {
    /**
     * Successful Response
     */
    200: TranscriptionResponse;
};

export type TranscribeSpeechApiTranscribePostResponse = TranscribeSpeechApiTranscribePostResponses[keyof TranscribeSpeechApiTranscribePostResponses];

export type SpeechToBrailleApiSpeechToBraillePostData = {
    body: BodySpeechToBrailleApiSpeechToBraillePost;
    path?: never;
    query: {
        /**
         * Braille Table
         */
        braille_table?: string;
        /**
         * Language
         *
         * Language code (e.g., 'en', 'es') - required
         */
        language: string;
        /**
         * Task
         */
        task?: string;
        /**
         * Word Timestamps
         */
        word_timestamps?: boolean;
    };
    url: '/api/speech-to-braille';
};

export type SpeechToBrailleApiSpeechToBraillePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SpeechToBrailleApiSpeechToBraillePostError = SpeechToBrailleApiSpeechToBraillePostErrors[keyof SpeechToBrailleApiSpeechToBraillePostErrors];

export type SpeechToBrailleApiSpeechToBraillePostResponses = {
    /**
     * Successful Response
     */
    200: SpeechToBrailleResponse;
};

export type SpeechToBrailleApiSpeechToBraillePostResponse = SpeechToBrailleApiSpeechToBraillePostResponses[keyof SpeechToBrailleApiSpeechToBraillePostResponses];

export type BrailleToSpeechApiBrailleToSpeechPostData = {
    body: BrailleToSpeechRequest;
    path?: never;
    query?: never;
    url: '/api/braille-to-speech';
};

export type BrailleToSpeechApiBrailleToSpeechPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrailleToSpeechApiBrailleToSpeechPostError = BrailleToSpeechApiBrailleToSpeechPostErrors[keyof BrailleToSpeechApiBrailleToSpeechPostErrors];

export type BrailleToSpeechApiBrailleToSpeechPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListVoicesApiVoicesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/voices';
};

export type ListVoicesApiVoicesGetResponses = {
    /**
     * Response List Voices Api Voices Get
     *
     * Successful Response
     */
    200: Array<VoiceInfo>;
};

export type ListVoicesApiVoicesGetResponse = ListVoicesApiVoicesGetResponses[keyof ListVoicesApiVoicesGetResponses];

export type OcrRecognizeApiOcrPostData = {
    body: BodyOcrRecognizeApiOcrPost;
    path?: never;
    query?: {
        /**
         * Language
         *
         * OCR language code (e.g., 'en', 'fr', 'ch')
         */
        language?: string | null;
    };
    url: '/api/ocr';
};

export type OcrRecognizeApiOcrPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OcrRecognizeApiOcrPostError = OcrRecognizeApiOcrPostErrors[keyof OcrRecognizeApiOcrPostErrors];

export type OcrRecognizeApiOcrPostResponses = {
    /**
     * Successful Response
     */
    200: OcrResponse;
};

export type OcrRecognizeApiOcrPostResponse = OcrRecognizeApiOcrPostResponses[keyof OcrRecognizeApiOcrPostResponses];

export type OcrToBrailleApiOcrToBraillePostData = {
    body: BodyOcrToBrailleApiOcrToBraillePost;
    path?: never;
    query?: {
        /**
         * Language
         *
         * OCR language code (e.g., 'en', 'fr', 'ch')
         */
        language?: string | null;
        /**
         * Braille Table
         *
         * Braille translation table
         */
        braille_table?: string;
    };
    url: '/api/ocr-to-braille';
};

export type OcrToBrailleApiOcrToBraillePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OcrToBrailleApiOcrToBraillePostError = OcrToBrailleApiOcrToBraillePostErrors[keyof OcrToBrailleApiOcrToBraillePostErrors];

export type OcrToBrailleApiOcrToBraillePostResponses = {
    /**
     * Successful Response
     */
    200: OcrToBrailleResponse;
};

export type OcrToBrailleApiOcrToBraillePostResponse = OcrToBrailleApiOcrToBraillePostResponses[keyof OcrToBrailleApiOcrToBraillePostResponses];
