// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * BackTranslationRequest
 *
 * Request model for braille-to-text back-translation
 */
export type BackTranslationRequest = {
    /**
     * Braille
     *
     * Braille text to translate back
     */
    braille: string;
    /**
     * Table
     *
     * Braille table filename to use
     */
    table: string;
};

/**
 * BackTranslationResponse
 *
 * Response model for back-translation
 */
export type BackTranslationResponse = {
    /**
     * Original Braille
     *
     * Original braille input
     */
    original_braille: string;
    /**
     * Text
     *
     * Back-translated text
     */
    text: string;
    /**
     * Table Used
     *
     * Table filename used
     */
    table_used: string;
    /**
     * Success
     *
     * Whether back-translation succeeded
     */
    success: boolean;
};

/**
 * Body_speech_to_braille_api_speech_to_braille_post
 */
export type BodySpeechToBrailleApiSpeechToBraillePost = {
    /**
     * Audio
     *
     * Audio file
     */
    audio: Blob | File;
};

/**
 * Body_transcribe_speech_api_transcribe_post
 */
export type BodyTranscribeSpeechApiTranscribePost = {
    /**
     * Audio
     *
     * Audio file (WAV, MP3, OGG, etc.)
     */
    audio: Blob | File;
};

/**
 * BrailleTable
 *
 * Represents a braille translation table
 */
export type BrailleTable = {
    /**
     * Filename
     *
     * Table filename (e.g., en-us-g2.ctb)
     */
    filename: string;
    /**
     * Display Name
     *
     * Human-readable name
     */
    display_name: string;
    /**
     * Language
     *
     * Language code (ISO 639)
     */
    language: string;
    /**
     * Grade
     *
     * Braille grade (g1, g2, etc.)
     */
    grade?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Health check response
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Liblouis Version
     */
    liblouis_version: string;
    /**
     * Asr Status
     */
    asr_status: string;
    /**
     * Asr Model
     */
    asr_model?: string | null;
    /**
     * Asr Device
     */
    asr_device?: string | null;
};

/**
 * SegmentTimestamp
 *
 * Segment-level information with word timestamps
 */
export type SegmentTimestamp = {
    /**
     * Id
     *
     * Segment ID
     */
    id: number;
    /**
     * Start
     *
     * Segment start time in seconds
     */
    start: number;
    /**
     * End
     *
     * Segment end time in seconds
     */
    end: number;
    /**
     * Text
     *
     * Segment text
     */
    text: string;
    /**
     * Words
     *
     * Word-level timestamps
     */
    words?: Array<WordTimestamp> | null;
    /**
     * Avg Logprob
     *
     * Average log probability
     */
    avg_logprob: number;
    /**
     * No Speech Prob
     *
     * No speech probability
     */
    no_speech_prob: number;
};

/**
 * SpeechToBrailleResponse
 *
 * Response for combined pipeline
 */
export type SpeechToBrailleResponse = {
    /**
     * Transcribed Text
     *
     * Transcribed speech
     */
    transcribed_text: string;
    /**
     * Braille
     *
     * Braille output
     */
    braille: string;
    /**
     * Language
     *
     * Detected language
     */
    language?: string | null;
    /**
     * Table Used
     *
     * Braille table used
     */
    table_used: string;
    /**
     * Audio Duration
     *
     * Audio duration
     */
    audio_duration?: number | null;
    /**
     * Segments
     *
     * Segment timestamps
     */
    segments?: Array<SegmentTimestamp> | null;
    /**
     * Success
     *
     * Success status
     */
    success: boolean;
};

/**
 * TranscriptionResponse
 *
 * Response model for speech transcription
 */
export type TranscriptionResponse = {
    /**
     * Text
     *
     * Transcribed text
     */
    text: string;
    /**
     * Language
     *
     * Detected or specified language
     */
    language?: string | null;
    /**
     * Duration
     *
     * Audio duration in seconds
     */
    duration?: number | null;
    /**
     * Segments
     *
     * Segment timestamps with words
     */
    segments?: Array<SegmentTimestamp> | null;
    /**
     * Success
     *
     * Whether transcription succeeded
     */
    success: boolean;
};

/**
 * TranslationRequest
 *
 * Request model for text-to-braille translation
 */
export type TranslationRequest = {
    /**
     * Text
     *
     * Text to translate to braille
     */
    text: string;
    /**
     * Table
     *
     * Braille table filename to use
     */
    table: string;
};

/**
 * TranslationResponse
 *
 * Response model for braille translation
 */
export type TranslationResponse = {
    /**
     * Original Text
     *
     * Original input text
     */
    original_text: string;
    /**
     * Braille
     *
     * Translated braille text (Unicode braille)
     */
    braille: string;
    /**
     * Table Used
     *
     * Table filename used for translation
     */
    table_used: string;
    /**
     * Success
     *
     * Whether translation succeeded
     */
    success: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WordTimestamp
 *
 * Word-level timestamp information
 */
export type WordTimestamp = {
    /**
     * Word
     *
     * The word text
     */
    word: string;
    /**
     * Start
     *
     * Start time in seconds
     */
    start: number;
    /**
     * End
     *
     * End time in seconds
     */
    end: number;
    /**
     * Probability
     *
     * Word confidence probability
     */
    probability: number;
};

export type HealthCheckGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type HealthCheckGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckGetResponse = HealthCheckGetResponses[keyof HealthCheckGetResponses];

export type ListTablesApiTablesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tables';
};

export type ListTablesApiTablesGetResponses = {
    /**
     * Response List Tables Api Tables Get
     *
     * Successful Response
     */
    200: Array<BrailleTable>;
};

export type ListTablesApiTablesGetResponse = ListTablesApiTablesGetResponses[keyof ListTablesApiTablesGetResponses];

export type TranslateToBrailleApiTranslatePostData = {
    body: TranslationRequest;
    path?: never;
    query?: never;
    url: '/api/translate';
};

export type TranslateToBrailleApiTranslatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranslateToBrailleApiTranslatePostError = TranslateToBrailleApiTranslatePostErrors[keyof TranslateToBrailleApiTranslatePostErrors];

export type TranslateToBrailleApiTranslatePostResponses = {
    /**
     * Successful Response
     */
    200: TranslationResponse;
};

export type TranslateToBrailleApiTranslatePostResponse = TranslateToBrailleApiTranslatePostResponses[keyof TranslateToBrailleApiTranslatePostResponses];

export type BackTranslateFromBrailleApiBackTranslatePostData = {
    body: BackTranslationRequest;
    path?: never;
    query?: never;
    url: '/api/back-translate';
};

export type BackTranslateFromBrailleApiBackTranslatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BackTranslateFromBrailleApiBackTranslatePostError = BackTranslateFromBrailleApiBackTranslatePostErrors[keyof BackTranslateFromBrailleApiBackTranslatePostErrors];

export type BackTranslateFromBrailleApiBackTranslatePostResponses = {
    /**
     * Successful Response
     */
    200: BackTranslationResponse;
};

export type BackTranslateFromBrailleApiBackTranslatePostResponse = BackTranslateFromBrailleApiBackTranslatePostResponses[keyof BackTranslateFromBrailleApiBackTranslatePostResponses];

export type TestTranslationApiTestTranslationGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test-translation';
};

export type TestTranslationApiTestTranslationGetResponses = {
    /**
     * Successful Response
     */
    200: TranslationResponse;
};

export type TestTranslationApiTestTranslationGetResponse = TestTranslationApiTestTranslationGetResponses[keyof TestTranslationApiTestTranslationGetResponses];

export type TranscribeSpeechApiTranscribePostData = {
    body: BodyTranscribeSpeechApiTranscribePost;
    path?: never;
    query?: {
        /**
         * Language
         */
        language?: string | null;
        /**
         * Task
         */
        task?: string;
        /**
         * Word Timestamps
         */
        word_timestamps?: boolean;
    };
    url: '/api/transcribe';
};

export type TranscribeSpeechApiTranscribePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranscribeSpeechApiTranscribePostError = TranscribeSpeechApiTranscribePostErrors[keyof TranscribeSpeechApiTranscribePostErrors];

export type TranscribeSpeechApiTranscribePostResponses = {
    /**
     * Successful Response
     */
    200: TranscriptionResponse;
};

export type TranscribeSpeechApiTranscribePostResponse = TranscribeSpeechApiTranscribePostResponses[keyof TranscribeSpeechApiTranscribePostResponses];

export type SpeechToBrailleApiSpeechToBraillePostData = {
    body: BodySpeechToBrailleApiSpeechToBraillePost;
    path?: never;
    query?: {
        /**
         * Braille Table
         */
        braille_table?: string;
        /**
         * Language
         */
        language?: string | null;
        /**
         * Task
         */
        task?: string;
        /**
         * Word Timestamps
         */
        word_timestamps?: boolean;
    };
    url: '/api/speech-to-braille';
};

export type SpeechToBrailleApiSpeechToBraillePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SpeechToBrailleApiSpeechToBraillePostError = SpeechToBrailleApiSpeechToBraillePostErrors[keyof SpeechToBrailleApiSpeechToBraillePostErrors];

export type SpeechToBrailleApiSpeechToBraillePostResponses = {
    /**
     * Successful Response
     */
    200: SpeechToBrailleResponse;
};

export type SpeechToBrailleApiSpeechToBraillePostResponse = SpeechToBrailleApiSpeechToBraillePostResponses[keyof SpeechToBrailleApiSpeechToBraillePostResponses];
